#!/bin/bash
if [ $# -lt 5 ];then
 echo "Usage:./a_mgu <admin user> <admin password> <database name> <user> <password>"
 exit
fi
mongo <<EOF
 use admin;
 db.auth('$1','$2');
 use $3;
 db.addUser('$4','$5');
EOF
