#!/bin/bash
if [ "$1" = "" ];then
 echo 'srsync <local dir> <remote address>'
 exit 0
fi
if [ "-h" = "$1" ];then
 echo 'srsync <local dir> <remote address>'
 exit 0
fi
if [ "-i" = "$1" ];then
 cp $0 /usr/bin
 exit 0
fi
pwd_=`pwd`
args=""
if [ -f "$pwd_/srsync.args" ];then
 args=`cat $pwd_/srsync.args`
fi
if [ "-c" = "$1" ];then
 /usr/bin/rsync -qaxvP --delete $args $2 $3
 exit 0
fi
for((i=0;1;i++));
do
 if [ -f "$1/inc.txt" ];then
  echo "syncing->inc->$i"
  /usr/bin/rsync -qaxvrP --delete --include=inc.txt --include=exc.txt --include-from=$1/inc.txt --exclude=* $args $1 $2
 else 
  if [ -f "$1/exc.txt" ];then
   echo "syncing->exc->$i"
   /usr/bin/rsync -qaxvrP --delete --exclude-from=$1/exc.txt $args $1 $2
  else
   echo "syncing->->$i"
   /usr/bin/rsync -qaxvrP --delete $args $1 $2
   fi
 fi
 sleep 8
done

