#!/bin/bash
name_d=$2
usr_n=$3
if [ "$4" != "" ];then
	name_d=$4
fi

if [ "$usr_n" == "" ];then
	usr_n=$name_d
fi 


install(){
	tpwd=`pwd`
	tpwd=${tpwd//\//\\\/}
	echo "s/RV_SRVD_HOME/$tpwd/g"
	sed "s/RV_SRVD_HOME/$tpwd/g" ./$name_d | sed "s/RV_SRVD_USR/$usr_n/g" >/etc/init.d/$name_d
	chmod +x /etc/init.d/$name_d

	mkdir /var/log/$name_d
	chown -R $usr_n /var/log/$name_d
	##
	chkconfig --add $name_d
	chkconfig $name_d on
	service $name_d start
	echo "Install Done..."
}
uninstall(){
	service $name_d stop
	rm -rf /var/log/$name_d
	chkconfig --del $name_d
	rm -f /etc/init.d/$name_d
	echo "Uninstall Done..."
}

case $1 in
 -i)
  install
 ;;
 -u)
  uninstall
 ;;
 *)
  echo Usage ./install.sh [-i|-u]
 ;;
esac
