#!/bin/bash
#
tpwd=`pwd`
tpwd=${tpwd//\//\\\/}
srv_h=$tpwd
exe_n=$2
usr_n=$3
srv_n=$4
arg_l="$5"

if [ "$usr_n" == "" ];then
	usr_n=$exe_n"d"
fi

if [ "$srv_n" == "" ];then
	srv_n=$usr_n
fi 


install(){
	echo "Install $srv_n by home($srv_h),exe($exe_n),user($usr_n)"
	echo "s/RV_SRVD_HOME/$tpwd/g"
	sed "s/RV_SRVD_HOME/$tpwd/g" ./srvd | sed "s/RV_SRVD_USR/$usr_n/g" | sed "s/RV_SRVD_EXE/$exe_n/g" | sed "s/RV_SRVD_SRV/$srv_n/g" | sed "s/RV_SRVD_ARG/$arg_l/g" >/etc/init.d/$srv_n
	chmod +x /etc/init.d/$srv_n

	mkdir /var/log/$srv_n
	chown -R $usr_n /var/log/$srv_n
	##
	chkconfig --add $srv_n
	chkconfig $srv_n on
	#service $srv_n start
	echo "Install $srv_n Done..."
}
uninstall(){
	service $srv_n stop
	rm -rf /var/log/$srv_n
	chkconfig --del $srv_n
	rm -f /etc/init.d/$srv_n
	echo "Uninstall $srv_n Done..."
}

case $1 in
 -i)
  install
 ;;
 -u)
  uninstall
 ;;
 *)
  echo Usage ./install.sh [-i|-u]
 ;;
esac
