#!/bin/bash
name_d=$1
yum install daemonize -y

useradd $name_d
mkdir /var/log/$name_d
chown -R $name_d /var/log/$name_d
##
cp ./$name_d /etc/init.d
chkconfig --add $name_d
chkconfig $name_d on
service $name_d start

